spring:
    datasource:
        driverClassName: org.postgresql.Driver
        password: 123
        url: jdbc:postgresql://localhost:5432/db_tl
        username: admin_tl
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                temp:
                    use_jdbc_metadata_defaults: false
        show-sql: true
