spring:
    datasource:
        driverClassName: org.postgresql.Driver
        password: 123
        url: jdbc:postgresql://localhost:5432/db_thelibrary?currentSchema=dev
        username: admin_tl
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
#        hibernate:
#            ddl-auto: update
        properties:
            hibernate:
                temp:
                    use_jdbc_metadata_defaults: false
        show-sql: true

logging:
    level:
        org:
            hibernate:
                SQL: DEBUG
                type:
                    descriptor:
                        sql:
                            BasicBinder: TRACE
